# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
                ('pub_date', models.IntegerField(default=0)),
            ],
        ),
    ]
