# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='pub_year',
        ),
    ]
