# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180312_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
