# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
